services:
  - type: web
    name: gold-carnival-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://gold-carnival-backend.onrender.com 